from datetime import date
from typing import  Any
from collections.abc import AsyncIterable

from langchain_core.messages import AIMessage, ToolMessage
from langchain_core.runnables import RunnableConfig
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.agents import create_agent
from langgraph.checkpoint.memory import MemorySaver

from tools import get_availability
from schemas import ResponseFormat

memory = MemorySaver()

class NicoAgent:
    """ NicoAgent - An agent to manage Nico's availability. """

    SUPPORTED_CONTENT_TYPES = ["text/plain", "text"]

    SYSTEM_INSTRUCTION = (
        "You are Nico's scheduling assistant. "
        "Your sole purpose is to use the 'get_availability' tool to answer questions about Nico's schedule for playing basketball. "
        "You will be provided with the current date to help you understand relative date queries like 'tomorrow' or 'next week'. "
        "Use this information to correctly call the tool with a specific date (e.g., 'YYYY-MM-DD'). "
        "If the user asks about anything other than scheduling basketball, "
        "politely state that you cannot help with that topic and can only assist with scheduling queries. "
        "Do not attempt to answer unrelated questions or use tools for other purposes. "
        "Set response status to input_required if the user needs to provide more information. "
        "Set response status to error if there is an error while processing the request. "
        "Set response status to completed if the request is complete."
    )

    def __init__(self):
        self.model = ChatGoogleGenerativeAI(model="gemini-1.5-flash")
        self.tools = [get_availability]

        self.graph = create_agent(
            model=self.model,
            tools=self.tools,
            system_prompt=self.SYSTEM_INSTRUCTION,
            checkpointer=memory,
            response_format=ResponseFormat,
        )

    def invoke(self, query, context_id):
        """
        Executes the agent synchronously, injecting current date context and returning the final processed response.     
        """
        config: RunnableConfig = {"configurable":{"thread_id": context_id}}
        today_str = f"La fecha de hoy es {date.today().strftime("%Y-%m-%d")}."
        argumented_query = f"{today_str}\n\nUser query: {query}"
        self.graph.invoke({"messages": [("user", argumented_query)]}, config=config)
        return self.get_agent_response(config)
    
    async def stream(self, query, context_id) -> AsyncIterable[dict[str, Any]]:
        """
        Executes the agent asynchronously, yielding a stream of events that includes intermediate status updates and the final response
        """
        today_str = f"La fecha de hoy es {date.today().strftime('%Y-%m-%d')}."
        augmented_query = f"{today_str}\n\nUser query: {query}"
        inputs = {"messages": [("user", augmented_query)]}
        config: RunnableConfig = {"configurable": {"thread_id": context_id}}

        for item in self.graph.stream(inputs, config, stream_mode="values"):
            message = item["messages"][-1]
            if (
                isinstance(message, AIMessage)
                and message.tool_calls
                and len(message.tool_calls) > 0
            ):
                yield {
                    "is_task_complete": False,
                    "require_user_input": False,
                    "content": "Checking Nico's availability...",
                }
            elif isinstance(message, ToolMessage):
                yield {
                    "is_task_complete": False,
                    "require_user_input": False,
                    "content": "Processing availability...",
                }

        yield self.get_agent_response(config)

    def get_agent_response(self, config):
        """
        Retrieves and parses the final structured response from the agent's graph state.

        This method extracts the 'structured_response' generated by the LLM from the 
        current graph state, interprets its status (input_required, completed, error), 
        and normalizes it into a client-ready dictionary.

        Args:
            config (RunnableConfig): Configuration dictionary containing the 'thread_id'
                                     needed to access the specific conversation state.

        Returns:
            dict: A standardized dictionary containing:
                - "is_task_complete" (bool): True if the request is fully resolved.
                - "require_user_input" (bool): True if the agent needs more details.
                - "content" (str): The message to be displayed to the user.
        """
        current_state = self.graph.get_state(config)
        structured_response = current_state.values.get("structured_response")

        if structured_response and isinstance(structured_response, ResponseFormat):
            if structured_response.status == "input_required":
                return {
                    "is_task_complete": False,
                    "require_user_input": True,
                    "content": structured_response.message,
                }
            if structured_response.status == "error":
                return {
                    "is_task_complete": False,
                    "require_user_input": True,
                    "content": structured_response.message,
                }
            if structured_response.status == "completed":
                return {
                    "is_task_complete": True,
                    "require_user_input": False,
                    "content": structured_response.message,
                }

        return {
            "is_task_complete": False,
            "require_user_input": True,
            "content": (
                "No podemos procesar su solicitud en este momento. "
                "Por favor, inténtelo de nuevo más tarde."
            ),
        }